-- V4: alerts. One alert per non-approved transaction, plus its human review lifecycle.

CREATE TABLE alerts
(
    -- PK strategy must match transactions.id exactly (see V1) so both entities
    -- can use the same @GeneratedValue strategy.
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- FK targets the surrogate key, not the client-supplied transaction_ref.
    transaction_id  BIGINT       NOT NULL,

    -- Snapshots of the evaluation, NOT NULL: an alert only exists after scoring,
    -- so both values are known at row-creation time (unlike transactions.risk_score).
    risk_score      SMALLINT     NOT NULL,
    decision        VARCHAR(20)  NOT NULL,

    -- Comma-joined rule codes, frozen at trigger time. Display only, never queried
    -- element-wise. Refactor point: aggregation by rule code -> child table.
    triggered_rules VARCHAR(255) NOT NULL,

    -- No DEFAULT: 'OPEN' is decided by application code, so it is defined there once.
    status          VARCHAR(20)  NOT NULL,

    -- DEFAULT here: the authoritative clock is the database's. Entity maps this
    -- column insertable = false, same as transactions.created_at.
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Null until reviewed. Kept consistent with status by ck_alerts_reviewed_at.
    reviewed_at     TIMESTAMPTZ,

    CONSTRAINT fk_alerts_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id),

    -- Database-level backstop for the consumer's idempotency guard.
    -- IRREVERSIBLE: locks in "at most one alert per transaction".
    CONSTRAINT uq_alerts_transaction_id UNIQUE (transaction_id),

    CONSTRAINT ck_alerts_risk_score_range
        CHECK (risk_score BETWEEN 0 AND 100),

    -- Only two of Decision's three values: an APPROVE alert is a business impossibility.
    CONSTRAINT ck_alerts_decision
        CHECK (decision IN ('REVIEW', 'BLOCK')),

    CONSTRAINT ck_alerts_status
        CHECK (status IN ('OPEN', 'CONFIRMED', 'FALSE_POSITIVE')),

    -- status and reviewed_at must move together: OPEN <=> not yet reviewed.
    CONSTRAINT ck_alerts_reviewed_at
        CHECK ((status = 'OPEN') = (reviewed_at IS NULL))
);

-- Justified by the ORDER BY that every alert-list request runs:
-- created_at DESC with id DESC as the unique tie-breaker.
-- transaction_id needs no index: the UNIQUE constraint already builds one.
CREATE INDEX idx_alerts_created_at_id ON alerts (created_at, id);